title: BioTesseract™
description: Cambridge Bioinformatics Solutions
logo: /assets/17867916/17073889/52aeca5e-5075-11e6-92a2-34884bd72d8c.png
theme: jekyll-theme-minimal
show_downloads: true
google_site_verification: 
plugins:
- jekyll-seo-tag
