(*
Program name: BioTesseract™ ONE Desktop
Version: 1.1.1 Build: 206
Authorship: The project was initially invented and developed by Dr Rafal Urniaz, actually it is developed by BioTesseract™ ONE community.
Description: This file is a part of the BioTesseract™ ONE Desktop project, for details please visit http://www.biotesseract.com
*)

Const

  //-- Communicates



  //-- Errors
       //-- Objects and Arrays
            error_1 = 'Object number is out of range ';

       //-- Files
            error_2 = 'File does not exist, please check filename and permissions to the file';
